#bind = "192.168.56.11:2222"
#url = "http://192.168.56.11:2222"

#blog_url = "http://192.168.56.11:1111"
path_regex = "<!--relative path \\((.*)\\)-->"
#blog_dir = "/home/zack/source/server/blog"
#blog_build_dir = "/home/zack/source/server/blog/public"
#dest_dir = "/home/zack/source/server/editor/target/blog"

build_command = ["zola", "build"]
create_revision = ["git", "commit", "-am"]
stage_revision = ["git", "add"]
reset_command = ["git", "clean", "-fd"]
list_revisions = ["git", "log", "--pretty=format:%h %ad %s"]
revert_revision = ["git", "revert"]
fix_revert = ["git", "revert", "--abort"]
#post_rebuild = ["git", "push"]

templates_dir = "templates"

bind = "127.0.0.1:2222"
url = "http://127.0.0.1:2222"
blog_url = "http://127.0.0.1:1111"
blog_dir = "C:/users/zack/source/server/blog"
blog_build_dir = "C:/users/zack/source/server/blog/public"
dest_dir = "C:/users/zack/source/server/editor/target/blog"